import type { Metadata } from "next";
import { Cinzel, Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components/layout";
import { Toaster } from "@/components/ui";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${inter.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col font-inter">
          <Header />

          <main className="container mx-auto flex-1 px-4 py-8 grid place-items-center bg-zinc-50 dark:bg-black">
            {children}
          </main>

          <Footer />
        </div>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
